export enum ApiPaths {
    CompaniesShortData = `/api/1.0/StocksInfo/report`,
    CompanyHistoricalDataAll = `/api/1.0/StocksInfo/historicalData`,
    CompanyForecastDataAll = `/api/1.0/StocksInfo/forecastData`,
    AuthLogin = `/api/1.0/Account/login`,
    AuthRegister = `/api/1.0/Account/register`,
    ForgotPasswordPost = `/api/1.0/Account/forgotPassword`,
    ModifyPasswordPut = `/api/1.0/Account/modifyPassword`,
    ResetPasswordPost = `/api/1.0/Account/resetPassword`,
    TradingContext = `/api/1.0/Portofolio/tradingContext`,
    BuyOrderGet = `/api/1.0/Portofolio/previewPlaceOrder`,
    SellOrderGet = `/api/1.0/Portofolio/previewPlaceOrder`,
    OrderPost = `/api/1.0/Portofolio/placeOrder`,
    RefillBalancePost = `/api/1.0/Portofolio/refillBalance`,
    TransactionsGrouped = `/api/1.0/Transactions/openTransactions`,
    TransactionsParticular = `/api/1.0/Transactions/openTransactionsForTicker/`,
    CloseTransactionPost = `/api/1.0/Transactions/closeTransaction`,
}